# Generated by Django 5.2.8 on 2025-12-04 18:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointDoctor', '0002_doctor_is_online_doctor_last_seen_videocallsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityschedule',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='videocallsession',
            name='appointment',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-rating', 'specialization']},
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='last_seen',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AppointmentNotification',
        ),
        migrations.DeleteModel(
            name='AvailabilitySchedule',
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
        migrations.DeleteModel(
            name='VideoCallSession',
        ),
    ]
