# Generated by Django 5.2 on 2025-09-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_audioanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioanalysis',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioanalysis',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='audioanalysis',
            name='emotion',
            field=models.CharField(blank=True, choices=[('neutral', 'Neutral'), ('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fearful', 'Fearful'), ('disgusted', 'Disgusted'), ('surprised', 'Surprised')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='audioanalysis',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
