# Generated by Django 5.2 on 2025-09-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_audioanalysis_confidence_audioanalysis_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='sound_analysis',
        ),
    ]
