# Generated by Django 5.2 on 2025-11-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_article_articleview_articlelike_articlerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='assessment_images/'),
        ),
    ]
