# Generated by Django 5.2 on 2025-11-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_assessment_captured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='captured_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='assessments/'),
        ),
    ]
