# Generated by Django 5.2.8 on 2025-11-24 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_assessment_captured_image_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_score', models.FloatField(default=0)),
                ('bmi_score', models.FloatField(default=0)),
                ('sleep_score', models.FloatField(default=0)),
                ('mood_score', models.FloatField(default=0)),
                ('mood_label', models.CharField(blank=True, max_length=20, null=True)),
                ('text_sentiment_score', models.FloatField(default=0)),
                ('text_emotion_score', models.FloatField(default=0)),
                ('text_negative_keywords_score', models.FloatField(default=0)),
                ('image_expression_score', models.FloatField(default=0)),
                ('image_fatigue_score', models.FloatField(default=0)),
                ('image_darkcircles_score', models.FloatField(default=0)),
                ('image_stressmicro_score', models.FloatField(default=0)),
                ('voice_tone_score', models.FloatField(default=0)),
                ('voice_pitch_score', models.FloatField(default=0)),
                ('voice_speed_score', models.FloatField(default=0)),
                ('voice_hesitation_score', models.FloatField(default=0)),
                ('voice_stress_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
