# Generated by Django 5.2.8 on 2025-11-30 18:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioanalysis',
            name='audio_file',
            field=models.FileField(upload_to=api.models.user_audio_path),
        ),
    ]
