# Generated by Django 5.2.8 on 2025-12-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_audioanalysis_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='captured_image_path',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='health_goal',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='weight',
        ),
    ]
