# Generated by Django 5.2.8 on 2025-12-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_assessment_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='captured_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
