# Generated by Django 5.2.8 on 2025-12-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_assessment_captured_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='text_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
